### ISSUE TITLE
Categoria vuota -> iniziale

### ISSUE THREAD

**Issue by EnricoGhiorzi** [Progetto-ItaCa/libro#20]
https://github.com/Progetto-ItaCa/libro/blob/e1e8e17e8be8b71910455caf04f8994100beb570/cap/01-categorie.tex#L148C14-L148C14

In analogia con la categoria terminale al punto successivo, la categoria vuota andrebbe chiamata iniziale.

**Comment by tetrapharmakon** [comment]
E' vero!
